# -*- coding: utf-8 -*-
"""Grocery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMxLITciVM2-yA7KpbDw-nPR3smrVjkE
"""

#Input price of three grocery items in $
a = float(input("Enter price of first item: "))
b = float(input("Enter price of second item: "))
c = float(input("Enter price of third item: "))
print(a,"$")
print(b,"$")
print(c,"$")
#Total price of items
total = a+b+c
#Discount applied
if total>50:
  discount = ((10/100)*total)
  final_cost = total - discount
else:
  discount = 0
#Billing details
print("Billing Details")
print("Total cost : ",total,"$")
print("Discount : ",discount,"$")
print("Cost to be paid : ",final_cost,"$")
print("Thank You for visiting")